
insert into authors (id, firstname, lastname) values (1, 'Emery', 'Kennicott');
insert into authors (id, firstname, lastname) values (2, 'Nikolia', 'Excell');
insert into authors (id, firstname, lastname) values (3, 'Wandie', 'Doumer');
insert into authors (id, firstname, lastname) values (4, 'Archibaldo', 'Lindsay');
insert into authors (id, firstname, lastname) values (5, 'Heddi', 'Spight');
insert into authors (id, firstname, lastname) values (6, 'Faber', 'Fenelow');
insert into authors (id, firstname, lastname) values (7, 'Obed', 'Critoph');
insert into authors (id, firstname, lastname) values (8, 'Gina', 'Moynham');
insert into authors (id, firstname, lastname) values (9, 'Robyn', 'Bierling');
insert into authors (id, firstname, lastname) values (10, 'Noam', 'Gasker');
insert into authors (id, firstname, lastname) values (11, 'Maurise', 'Cawston');
insert into authors (id, firstname, lastname) values (12, 'Rosanna', 'Erley');
insert into authors (id, firstname, lastname) values (13, 'Cindee', 'Jerrems');
insert into authors (id, firstname, lastname) values (14, 'Liuka', 'Shortcliffe');
insert into authors (id, firstname, lastname) values (15, 'Kathlin', 'Gianni');
insert into authors (id, firstname, lastname) values (16, 'Meridel', 'Lyes');
insert into authors (id, firstname, lastname) values (17, 'Eolanda', 'Benoit');
insert into authors (id, firstname, lastname) values (18, 'Kassi', 'Langlands');
insert into authors (id, firstname, lastname) values (19, 'Leigh', 'Ashburne');
insert into authors (id, firstname, lastname) values (20, 'Findley', 'Schwier');
insert into authors (id, firstname, lastname) values (21, 'Eleen', 'Gowers');
insert into authors (id, firstname, lastname) values (22, 'Curr', 'Jakoubek');
insert into authors (id, firstname, lastname) values (23, 'Ly', 'Perazzo');
insert into authors (id, firstname, lastname) values (24, 'Rubie', 'Stoakley');
insert into authors (id, firstname, lastname) values (25, 'Waylon', 'Newlin');
insert into authors (id, firstname, lastname) values (26, 'Louis', 'Hillan');
insert into authors (id, firstname, lastname) values (27, 'Farand', 'Lorence');
insert into authors (id, firstname, lastname) values (28, 'Julia', 'De La Hay');
insert into authors (id, firstname, lastname) values (29, 'Melonie', 'Rolling');
insert into authors (id, firstname, lastname) values (30, 'Blanche', 'Krysiak');

insert into books (id, price, price_old, title, author_id) values (1, '$229.00', '$829.69', 'Bluebeard (Landru)', 1);
insert into books (id, price, price_old, title, author_id) values (2, '$431.58', '$762.66', 'Tom and Jerry: A Nutcracker Tale', 2);
insert into books (id, price, price_old, title, author_id) values (3, '$355.52', '$847.54', 'Real McCoy, The', 3);
insert into books (id, price, price_old, title, author_id) values (4, '$370.38', '$589.78', 'Secrets of Eden', 4);
insert into books (id, price, price_old, title, author_id) values (5, '$151.82', '$646.22', 'Lust for Gold (Duhul aurului)', 5);
insert into books (id, price, price_old, title, author_id) values (6, '$161.09', '$582.99', 'Prison Terminal: The Last Days of Private Jack Hall', 6);
insert into books (id, price, price_old, title, author_id) values (7, '$418.84', '$962.88', 'Pirates! Band of Misfits, The', 7);
insert into books (id, price, price_old, title, author_id) values (8, '$477.01', '$715.53', 'Nanny Diaries, The', 8);
insert into books (id, price, price_old, title, author_id) values (9, '$115.82', '$864.85', 'Newcastle', 9);
insert into books (id, price, price_old, title, author_id) values (10, '$162.86', '$696.94', 'Winter of Discontent', 10);
insert into books (id, price, price_old, title, author_id) values (11, '$252.54', '$508.39', 'Pleasantville', 11);
insert into books (id, price, price_old, title, author_id) values (12, '$253.00', '$852.89', 'Dr. Terrors House of Horrors', 12);
insert into books (id, price, price_old, title, author_id) values (13, '$436.18', '$703.67', 'Fifth Estate, The', 13);
insert into books (id, price, price_old, title, author_id) values (14, '$324.29', '$963.35', 'Topo, El', 14);
insert into books (id, price, price_old, title, author_id) values (15, '$449.65', '$743.39', 'Krrish', 15);
insert into books (id, price, price_old, title, author_id) values (16, '$459.26', '$728.87', 'Something from Nothing: The Art of Rap', 16);
insert into books (id, price, price_old, title, author_id) values (17, '$480.28', '$866.46', 'Quiller Memorandum, The', 17);
insert into books (id, price, price_old, title, author_id) values (18, '$152.79', '$996.99', 'Arizona Dream', 18);
insert into books (id, price, price_old, title, author_id) values (19, '$284.67', '$803.85', 'Dangerous Place, A', 19);
insert into books (id, price, price_old, title, author_id) values (20, '$238.36', '$619.87', 'Unprecedented: The 2000 Presidential Election', 20);
insert into books (id, price, price_old, title, author_id) values (21, '$394.06', '$683.04', 'Hour of the Wolf (Vargtimmen)', 21);
insert into books (id, price, price_old, title, author_id) values (22, '$281.95', '$941.69', 'Afflicted', 22);
insert into books (id, price, price_old, title, author_id) values (23, '$430.50', '$727.01', 'Kein Bund Leben', 23);
insert into books (id, price, price_old, title, author_id) values (24, '$269.97', '$512.48', 'Jungle Man-Eaters', 24);
insert into books (id, price, price_old, title, author_id) values (25, '$157.16', '$895.69', 'Nanny McPhee', 25);
insert into books (id, price, price_old, title, author_id) values (26, '$422.84', '$806.45', 'Red Obession', 26);
insert into books (id, price, price_old, title, author_id) values (27, '$331.12', '$685.84', 'We Are the Best!', 27);
insert into books (id, price, price_old, title, author_id) values (28, '$471.95', '$555.60', 'Uninvited Guest', 28);
insert into books (id, price, price_old, title, author_id) values (29, '$311.93', '$780.63', 'Guard, The', 29);
insert into books (id, price, price_old, title, author_id) values (30, '$105.58', '$564.54', 'Triangle', 30);
