package com.example.BookShop.entity;

import com.fasterxml.jackson.annotation.JsonIgnore;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.*;
import javax.persistence.*;
import java.util.ArrayList;
import java.util.List;

@Data
@AllArgsConstructor
@NoArgsConstructor
@Entity
@ApiModel(description = "data model of author entity")
@Table(name = "authors")
public class Author {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @ApiModelProperty(value = "author id generated by db", position = 1)
    private int id;
    @ApiModelProperty(value = "first name of author", example = "Charlie", position = 2)
    private String firstname;
    @ApiModelProperty(value = "last name of author", example = "Lame", position = 3)
    private String lastname;

    @Column(columnDefinition = "VARCHAR(255)")
    private String photo;

    @Column(columnDefinition = "VARCHAR(255)")
    private String slug;

    @Column(columnDefinition = "TEXT")
    private String description;

    @JsonIgnore
    @OneToMany(mappedBy = "author")
    private List<Book> bookList = new ArrayList<>();

    public Author(int id, String firstname, String lastname, String photo, String slug, String description) {
        this.id = id;
        this.firstname = firstname;
        this.lastname = lastname;
        this.photo = photo;
        this.slug = slug;
        this.description = description;
    }

    @Override
    public String toString() {
        return firstname + " " + lastname;
    }
}